### PR TITLE
Option to filter rows

### PR DESCRIPTION
**Pull request by thiagotalma**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by samdark** [comment]
Do we have that many files generated that a filter is required?

**Comment by samdark** [comment]
Probably yes in case `*` is used. OK. Makes sense.

**Comment by thiagotalma** [comment]
@samdark That's right. Do you get the idea.

Try to catch only the query files in a project with 57 tables that will understand what we are talking about.  :wink:

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request closed without merging**
