### PR TITLE
Update action.php

### PR DESCRIPTION
**Pull request by amin0256**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | none

### CODE REVIEW

**Comment by samdark** [comment]
Why?

**Comment by amin0256** [comment]
@samdark because when you copy and paste that in a controller, that not work.
controller is in `@app/controllers/TestController` and model is in `@app/models/Test`, now compiler want to find it in `@app/controllers/app/models/Test`.
sorry for my bad language. 
tnx <3

**Comment by cebe** [comment]
` $generator->modelClass ` should already be an absolute class name including the namespace

**Comment by amin0256** [comment]
@cebe it will make a namespace like 'app\models\User' 
do you can check it ?

**Comment by cebe** [comment]
The issue is valid but it should be ensured in the Generator that modelClass is absolute in all places.

**Comment by cebe** [comment]
Merged, thank you!

**Comment by amin0256** [comment]
thank you dear @cebe <3

**Pull request merged**
