### PR TITLE
Update use of ::className() in model/Generator

### PR DESCRIPTION
**Pull request by yoshifp**
Update use of ::className() in model/Generator to ::class

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | N/A

### CODE REVIEW

**Comment by samdark** [comment]
We support 5.4. Can't merge it.

**Comment by rob006** [comment]
@samdark both app templates already requires PHP 5.6.

**Comment by samdark** [comment]
Yes but framework is not app template.

**Comment by rob006** [comment]
And Gii is not part of the core framework. App templates is just an example that we should move on - PHP 5.4 EOLed over 4 years ago. For me it a bug that Gii targets that old PHP version and generates code with methods that were deprecated in core.

**Comment by samdark** [comment]
1. PHP version in composer.json should be adjusted.
2. https://travis-ci.com/github/yiisoft/yii2-gii/jobs/309318715

**Pull request closed without merging**
