### PR TITLE
New feature for the issue #551

### PR DESCRIPTION
**Pull request by evil1**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #551

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Please add a line to CHANGELOG. Thanks.

**Comment by evil1** [comment]
> Please add a line to CHANGELOG. Thanks.

Done

**Comment by samdark** [comment]
Forgot to push?

**Comment by evil1** [comment]
> Forgot to push?

Added changelog to another issue, related to `yiisoft/db` :)

**Comment by samdark** [comment]
Thank you!

**Comment by rob006** [comment]
I don't get it. By default `formName()` is used as form name in `load()` and while generating inputs. After this change form name is specified explicitly for `load()`, but for inputs generation value from `formName()` is still used. So if you want to change form name you need to change it in two places now?

**Comment by samdark** [comment]
@evil1 ?

**Comment by evil1** [comment]
> I don't get it. By default `formName()` is used as form name in `load()` and while generating inputs. After this change form name is specified explicitly for `load()`, but for inputs generation value from `formName()` is still used. So if you want to change form name you need to change it in two places now?

`formName()` returns a class name (via `ReflectionClass::getShortName()` under the hood).
We are explicitly passing the same class name, to be able to pass custom form name (especially empty string) to the `search()` method.
Why do we have to change it somewhere else?

**Comment by rob006** [comment]
> `formName()` returns a class name (via `ReflectionClass::getShortName()` under the hood).

`formName()` could be overwritten. Previously if I wanted to remove form name from search form, all I needed is to overwrite `formName()` to return empty string - new value was be respected both in view with search form and in `load()`. Now it is not enough - I also need to change default param value in `search()`, because `search()` ignores `formName()` after this PR.

So this solution is suboptimal for code that Gii generates, just to cover hypothetical (and IMO quite niche) use case.

**Comment by evil1** [comment]
Got it. Should I revert this PR back?

**Comment by rob006** [comment]
Changing method signature to `search($params, $formName = null)` should fix the problem I mentioned in https://github.com/yiisoft/yii2-gii/pull/552#issuecomment-2565213807. But I'm still not sure if this use case is common enough to have it in default template.

**Comment by evil1** [comment]
Should I submit new PR to fix this issue?

**Comment by samdark** [comment]
Yes. Please.

**Comment by evil1** [comment]
> Yes. Please.

Added a PR [here](https://github.com/yiisoft/yii2-gii/pull/553). Set `$formName = null` as advised by @rob006

**Pull request merged**
