### PR TITLE
Update model.php to generate const properties for Model's attributes

### PR DESCRIPTION
**Pull request by mnglkhn**
Generate const values for model's property names. 
Prefixed by 'COL_', can then be accessed like Model::COL_PROP_NAME.

### CODE REVIEW

**Comment by samdark** [comment]
Why do we need it?

**Comment by mnglkhn** [comment]
When working with an IDE, such as PhpStorm, allows for quick model introspection, without the need to guess what the actual field names are. Especially when you fetch a model as an array. At that point you need to know the array key names, in order to get the values. Cuts down on errors.
I just type Model::COL_ and then CTRL+SPACE and get all the Model columns.

**Comment by samdark** [comment]
If you're working with objects, modern IDEs are already using `@property` declarations and autocompleting properties.

**Comment by mnglkhn** [comment]
hmm, I might be missing something and I am curious how would that work in the following case:

$category = Category->find()->where([...])->toArray();
echo $category['label'];

which would become:
echo $category[Category::COL_LABEL];

For some reason, I find the current way prone to errors. Plus you would need to jump to the model definition to see the actual column name and then copy it in order to correctly paste it back where you need it in your workflow.

**Comment by samdark** [comment]
It won't work with arrays, of course.

**Comment by samdark** [comment]
```php
$category = Category->find()->where([...])->one();
echo $category->label;
```

**Comment by mnglkhn** [comment]
Of course, if you keep the model object, then you have access to its properties, no argument there.
My thinking was that somebody might want to move arrays around for increased speed and lower memory size usage.

**Comment by samdark** [comment]
Well, that's not reall common case so I think it's better for you to keep it as custom template for now. Will reconsider if more people will ask for it.

**Pull request closed without merging**
