### PR TITLE
Update Generator.php

### PR DESCRIPTION
**Pull request by claudejanz**
make generateProperties protected
to be able to call it if you create your own Generators

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by schmunk42** [comment]
LGTM in general.

But could someone revise the current public/protected/private declarations, ie.

```
public function generateRules($tabl
public function generateLabels($table)
private function generateManyManyRelations($table, $fks, $relations)
```

Haven't digged into the code too much, I just wondered why some `generate...` methods are public, some protected and some private.

**Comment by claudejanz** [comment]
for me all generate... functions should be protected.

**Comment by claudejanz** [comment]
I have created a DoubleModel generator with a BaseModel identical to the one generated by this plugin and a other model overwriting the BaseModel for overwriting rules, behaviors etc...
This is usfull if I make a db modification. I just have to regenerate BaseModels.
https://github.com/claudejanz/yii2-mygii

**Comment by claudejanz** [comment]
@samdark : done

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
