### PR TITLE
Sort the labels alphabetically

### PR DESCRIPTION
**Pull request by thiagotalma**
In order to facilitate the location of the labels when we have models with a large number of attributes.

### CODE REVIEW

**Comment by klimov-paul** [comment]
I don't think such change should be made. Curretly labels are generated in the same order attributes are fetched from database. Usually people prefer them in this way.

For example: assume I have a table 'Item', which has columns: 'id', 'active', 'name'. I prefer to have the attributes listed in the order I gave them, while creating table: 'id', 'active', 'name'. But with this change the order will be following: 'active', 'id', 'name'.

Although, if such change applied, same sorting should be used, while composing `@property` PHP docs.

**Comment by thiagotalma** [comment]
Hello @klimov-paul ,

It really is not a good option to force the sort.
Nothing is better to give the option to the developer.

**Comment by ruffiem** [comment]
It depends on the developer. For me, having the cloning the table structure makes more sense. Tho, I understand your point of view @thiagotalma

**Comment by samdark** [comment]
Being an option it complicates the form while rare developer will prefer ID as non-first field. Thanks for proposal but it won't be merged.

**Pull request closed without merging**
