### PR TITLE
Transparency issue with the shown modal dialog.

### PR DESCRIPTION
**Pull request by glodov**
More information about a bug you can find here: https://github.com/yiisoft/yii2-gii/issues/524 or here in the video https://youtu.be/86Lc_MJ9jKQ the solution is here: https://youtu.be/o4FS0GH39YU

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/yii2-gii/issues/524

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Please add a line for CHANGELOG. Thanks.

**Comment by glodov** [comment]
> Please add a line for CHANGELOG. Thanks.

Should I add a 2.2.7 version there?

**Comment by samdark** [comment]
No. Reuse latest.

**Comment by glodov** [comment]
> No. Reuse latest.

Here we go: https://github.com/yiisoft/yii2-gii/pull/526

**Comment by samdark** [comment]
No need for a second pull request. You can just push additional commit to the same `patch-1` branch and the commit will end up here.

**Comment by glodov** [comment]
> No need for a second pull request. You can just push additional commit to the same `patch-1` branch and the commit will end up here.

Thanks.
Done.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
