### PR TITLE
update syntax of Late Static Binding

### PR DESCRIPTION
**Pull request by bscheshirwork**
I think we need generate a new-style code "in 2k17"

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes/no
| Breaks BC?    | template will be changed
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Can't do it till Yii 2.1 is released.

**Comment by bscheshirwork** [comment]
@samdark :suspect: Yii 2.1? 
2.1 required `php 7` or something else?

now I can see problem
```
        "php": ">=5.4.0",
```
5.5 needed :crying_cat_face:

**Comment by cebe** [comment]
> 5.5 needed 😿

exactly. Should be done in a 2.1 version.

**Comment by klimov-paul** [comment]
duplicates #159

**Pull request closed without merging**
