### PR TITLE
Changed visibility of model generator methods

### PR DESCRIPTION
**Pull request by WinterSilence**
First step to fix issue #439

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #439

### CODE REVIEW

**Comment by bizley** [comment]
It would be better to make all changes in one PR. Please explain reasoning behind this.

**Comment by WinterSilence** [comment]
@bizley I prefer to solve it step by step, small PR's = short discussion and quick adoption

**Comment by WinterSilence** [comment]
@samdark do you have any other suggestions on how to fix  #439?

**Comment by samdark** [comment]
@WinterSilence the question should be the opposite. Visibility of methods should stay as low as possible if they're not used from outside. From the PR it isn't clear what the change is for.

**Pull request closed without merging**
