### PR TITLE
Added return types, removed unused Yii from model.php, replaced imports

### PR DESCRIPTION
**Pull request by Erkinbek**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | Added return types

### CODE REVIEW

**Comment by samdark** [comment]
It won't work with older PHP versions.

**Comment by uldisn** [comment]
> It won't work with older PHP versions.

If create  own templates for each PHP version, it will work.

**Comment by Erkinbek** [comment]
All time when i generate code with gii, my idea (PHPStorm) will shows this lines as not optimized code. So if people are using old versions of php, just need close this PR. Thank you for your attention :)

**Comment by uldisn** [comment]
Idea no bad! In https://github.com/yiisoft/yii2-gii/blob/master/src/generators/model/Generator.php#L313 
```
if (phpversion() < '5.2' ) {
    $template = 'model_52.php';
} elseif {phpversion() >= '5.2' &&  phpversion() < '5.7'} {
   $template = 'model_52_57.php';
} elseif {phpversion() >= '5.7' &&  phpversion() < '7.4'} {
   $template = 'model_57_74.php';
} {
   $template = 'model_74.php';
}
```

For each PHP version own model_*php.

**Comment by Erkinbek** [comment]
OK. I'll fix it

**Pull request closed without merging**
