### PR TITLE
Translate for pt-BR (BRAZIL)

### PR DESCRIPTION
**Pull request by lukBarros**
20% done!

### CODE REVIEW

**Comment by lukBarros** [comment]
Failed in CI job? Whats?

**Comment by samdark** [comment]
Ignore it ;)

**Comment by lukBarros** [comment]
ok I will continue with the translation of this project and submit changes but to finish.

Samdark, after much trying until I found a help point which was accepted - Thank you, I hope to contribute more.

**Comment by lukBarros** [comment]
Hi @samdark  item  down! Translate 100% done in ptBR.

:)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-gii/commit/188000d505cfc914cf8b61c8628514bd6ad4086f

Thanks!

**Pull request closed without merging**
