### PR TITLE
Added PHPDoc to support the autocomplete for findOne() and findAll()

### PR DESCRIPTION
**Pull request by paulzi**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

### CODE REVIEW

**Comment by SilverFire** [comment]
Methods `findOne()` and `fineAll()` are declared in BaseActiveRecord and highlighting works without PHPDocs. What is the reason for this change? Or am I missing something?

**Comment by paulzi** [comment]
findOne() and findAll() return self|null, in PHPStorm autocompletion does not work:
Sample

**Comment by SilverFire** [comment]
Ah, than missing. @samdark do you know a better way?

**Comment by samdark** [comment]
Does it work for `static` only w/o `null`?

**Comment by paulzi** [comment]
Hmm.. Yes!
If I remove the `null` from PHPDoc `@return static|null` in the `BaseActiveRecord::findOne()` autocompletion works normally in PHPStorm. I'm close this pull-request and open new issue.

**Pull request closed without merging**
