### PR TITLE
avoid space after uncomment

### PR DESCRIPTION
**Pull request by bscheshirwork**
Result:
```php
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'attribute2',
            'attribute3',
            'attribute4',
            'attribute5',
           // 'attribute6',
           // 'attribute7',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

```
```php
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'attribute2',
            'attribute3',
            'attribute4',
            'attribute5',
            'attribute6',
            'attribute7',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

```

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no

### CODE REVIEW

**Comment by rob006** [comment]
I would rather put `//` at the beginning of line or just remove space after `//`. Many formatters will fix alignment of commented line anyway, so this will not change that much.

**Comment by bscheshirwork** [comment]
Yes
Alternative method is remove space after `//`

```php
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'attribute2',
            'attribute3',
            'attribute4',
            'attribute5',
            //'attribute6',
            //'attribute7',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

```

**Comment by bscheshirwork** [comment]
Repair my Engrish please :smile_cat:

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
