### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by loveorigami**
For include bootstrap 3

### CODE REVIEW

**Comment by cebe** [comment]
will it break with bootstrap4 ?

**Comment by samdark** [comment]
@loveorigami could you explain the change?

**Comment by loveorigami** [comment]
@cebe 
today I clear cache in my composer and install packages. 
```"yiisoft/yii2-bootstrap": "~2.0"```
I got bootstrap 4

**Comment by loveorigami** [comment]
Next I change to ```"yiisoft/yii2-bootstrap": "~2.0.0"```
And get only 2.0.0 version

**Comment by samdark** [comment]
OK. Thanks for explaining. Merged.

**Comment by cebe** [comment]
this looks like you messed something up with your composer.json,

1. "twbs/boostrap" should not be loaded in any case.
2. downgrade does not work well with composer asset plugin unless you disable this feature: https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#disable-the-import-filter-using-the-installed-packages

The problem does not seem related to this entry in composer.json.
If gii works without problems with bootstrap4, we should not limit the dependency here.

**Comment by samdark** [comment]
Anyway, the change is consistent with project templates and overall it makes sense to limit version like that.

**Comment by cebe** [comment]
I'd still prefer to check whether gii works with bootstrap4. Otherwise it would be impossible to use Gii 2.0.x with projects that use bootstrap4, and we'd need a 2.1 release of Gii only because of the bootstrap version constraint. Would be good to avoid that if possible.

**Pull request merged**
