### PR TITLE
Added support for field types 'date', 'datetime' & 'time'

### PR DESCRIPTION
**Pull request by mohamed-nazim**
Added input field of type 'date', 'datetime' & 'time' in form/search fields.

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by WinterSilence** [comment]
format of input(`<input type="date/time/datetime-local" ...>`) value not same to DB formats form date/time/datetime

**Comment by mohamed-nazim** [comment]
> format of input(`<input type="date/time/datetime-local" ...>`) value not same to DB formats form date/time/datetime i.e. you need convert value before save

Yes agree. This is current browser standards for date / date time input field and as such form renderers should not be responsible for db functions imho 🤔

**Comment by mohamed-nazim** [comment]
Sorry... this got a bit messy trying to rename the branch 🙏

**Comment by WinterSilence** [comment]
@mohamed-nazim where's your browsers and databases tests?
read https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/datetime-local#handling_browser_support

**Pull request closed without merging**
