### PR TITLE
fix incorrect generator of title for crud update view

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #382

### CODE REVIEW

**Comment by bscheshirwork** [comment]
#363

**Comment by samdark** [comment]
@bscheshirwork please add a line to CHANGELOG.

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by ricpelo** [comment]
This PR seems to bring #328 to life again :cry: .

**Comment by bscheshirwork** [comment]
@ricpelo $generator->getNameAttribute() must return 'id' in your case?

**Comment by ricpelo** [comment]
That's right. As you can see in #328, the problem is that `update.php` incorrectly contains `'Update Socios: {nameAttribute}'` instead of `'Update Socios: ' . $model->id`. It was a problem I solved almost a year ago using PR #329, but with the latest changes it's now unfixed again.

**Comment by ricpelo** [comment]
PR #383 re-fix #328 in the same way as before.

**Comment by bscheshirwork** [comment]
Look like incorrect work of $generator->getNameAttribute() without 'name' attribute

**Comment by ricpelo** [comment]
@bscheshirwork Just tested, and my PR #387 works OK on every case, with & without 'name' attribute, and with & without i18n. These are the generated code on every case:

## With 'name' attribute, no i18n:
```php
$this->title = 'Update Generos: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Generos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
```

## With 'name' attribute and i18n:
```php
$this->title = Yii::t('app', 'Update Generos: {name}', [
    'name' => '' . $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Generos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
```

## Without 'name' attribute, no i18n:
```php
$this->title = 'Update Generos: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Generos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
```

## Without 'name' attribute, with i18n:
```php
$this->title = Yii::t('app', 'Update Generos: {name}', [
    'name' => '' . $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Generos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
```

**Comment by ricpelo** [comment]
@bscheshirwork `$generator->getNameAttribute()` works OK, with & without 'name' attribute:

- With 'name' attribute, it returns `name`.
- Without 'name' attribute, it returns `id`.

The problem is in bad usage of the `strtr()` function in `src/generators/crud/default/views/update.php` file when used without i18n. My PR #387 fixes that.

**Pull request merged**
