### PR TITLE
Added unit test for Module::checkAccess()

### PR DESCRIPTION
**Pull request by rhertogh**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes (but requires #458)
| Fixed issues  | -

### CODE REVIEW

**Comment by rhertogh** [comment]
Requires #458 for `testCheckAccess` to pass.

**Comment by rob006** [comment]
If these are tests for #458, they should be added to #458. Creating separate PR for tests only is confusing and harder to review.

**Comment by rhertogh** [comment]
> If these are tests for #458, they should be added to #458. Creating separate PR for tests only is confusing and harder to review.

These tests are not specific for #458 but mainly for existing code, only a small portion is covering 458. I could remove that portion from this pull request, but then non-related code would be added to 458 or a third pull request would be required.

**Comment by rob006** [comment]
I don't see a problem to include these tests in #458, they are related and it certainly makes more sense than dependency on PR without tests (so you need to merge PR without knowing it actually works).

**Comment by bizley** [comment]
Please add those tests to #458

**Pull request closed without merging**
